import { IncomingMessage } from 'node:http';

import { Params } from 'nestjs-pino';
import { stdTimeFunctions } from 'pino';

import { NodeEnvironment } from 'src/config/environment';

/** Maps the project's LOG_LEVEL values onto pino levels. */
const PINO_LEVELS: Record<string, string> = {
  debug: 'debug',
  log: 'info',
  warn: 'warn',
  error: 'error',
  silent: 'silent',
};

/** Paths (pino-redact syntax) whose values must never reach the log output. */
export const REDACTED_PATHS: string[] = [
  'req.headers.authorization',
  'req.headers.cookie',
  'res.headers["set-cookie"]',
  'password',
  'refreshToken',
  'accessToken',
  '*.password',
  '*.refreshToken',
  '*.accessToken',
  'req.body',
];

const REDACTED_PLACEHOLDER = '[REDACTED]';
const PRETTY_TARGET = 'pino-pretty';

const routes = new WeakMap<object, string>();

export function rememberRoute(rawRequest: object, route: string | undefined): void {
  if (route) {
    routes.set(rawRequest, route);
  }
}

export function resolvePinoLevel(level: string): string {
  return PINO_LEVELS[level] ?? 'info';
}

/** Strips the query string, which may carry tokens or personal data. */
function pathOf(url: string | undefined): string {
  return (url ?? '').split('?')[0] ?? '';
}

/**
 * Request ids are generated by Fastify (genReqId) and stored on the raw request, so pino-http
 * logs the same id that the response envelope returns as `requestId`.
 */
export function buildLoggerParams(
  logLevel: string,
  nodeEnvironment: NodeEnvironment,
  resolveRequestId: (request: IncomingMessage) => string,
): Params {
  const isDevelopment = nodeEnvironment === NodeEnvironment.DEVELOPMENT;
  return {
    pinoHttp: {
      level: resolvePinoLevel(logLevel),
      timestamp: stdTimeFunctions.isoTime,
      quietResLogger: true,
      genReqId: resolveRequestId,
      redact: { paths: REDACTED_PATHS, censor: REDACTED_PLACEHOLDER },
      serializers: {
        req: (request: { id: string; method: string; url: string }) => ({
          method: request.method,
          path: pathOf(request.url),
        }),
        res: (response: { statusCode: number }) => ({ statusCode: response.statusCode }),
      },
      customProps: (request: IncomingMessage) => ({
        requestId: resolveRequestId(request),
        route: routes.get(request),
      }),
      customLogLevel: (_request, response, error) =>
        error || response.statusCode >= 500 ? 'error' : 'info',
      customSuccessMessage: (request, response) =>
        `${request.method} ${pathOf(request.url)} ${response.statusCode}`,
      customErrorMessage: (request, response) =>
        `${request.method} ${pathOf(request.url)} ${response.statusCode}`,
      transport: isDevelopment
        ? { target: PRETTY_TARGET, options: { singleLine: true, translateTime: 'SYS:HH:MM:ss' } }
        : undefined,
    },
    assignResponse: true,
    renameContext: 'context',
  };
}
