/** Static demo catalog: categories, suppliers and products (prices in VND, whole units only). */

export interface DemoCategory {
  key: string;
  code: string;
  name: string;
  description: string;
  isActive: boolean;
  /** Relative sales volume of the category. */
  weight: number;
  supplierKey: string;
}

export interface DemoSupplier {
  key: string;
  name: string;
  phone: string;
  email: string;
  address: string;
  note: string;
  isActive: boolean;
}

export interface DemoProductSpec {
  categoryKey: string;
  name: string;
  unit: string;
  price: number;
}

export const CATEGORIES: DemoCategory[] = [
  {
    key: 'drink',
    code: 'DU',
    name: 'Đồ uống',
    description: 'Nước giải khát, bia, trà, cà phê đóng chai/lon',
    isActive: true,
    weight: 5,
    supplierKey: 'anphat',
  },
  {
    key: 'candy',
    code: 'BK',
    name: 'Bánh kẹo',
    description: 'Bánh quy, kẹo, snack',
    isActive: true,
    weight: 3,
    supplierKey: 'haiha',
  },
  {
    key: 'milk',
    code: 'SU',
    name: 'Sữa & chế phẩm',
    description: 'Sữa tươi, sữa chua, phô mai',
    isActive: true,
    weight: 3.5,
    supplierKey: 'binhminh',
  },
  {
    key: 'noodle',
    code: 'MI',
    name: 'Mì gói & đồ khô',
    description: 'Mì ăn liền, gạo, miến, đồ khô',
    isActive: true,
    weight: 4,
    supplierKey: 'hoabinh',
  },
  {
    key: 'spice',
    code: 'GV',
    name: 'Gia vị',
    description: 'Nước mắm, dầu ăn, đường, hạt nêm',
    isActive: true,
    weight: 2.5,
    supplierKey: 'namviet',
  },
  {
    key: 'beauty',
    code: 'HM',
    name: 'Hóa mỹ phẩm',
    description: 'Chăm sóc cá nhân, tẩy rửa, giấy',
    isActive: true,
    weight: 2,
    supplierKey: 'achau',
  },
  {
    key: 'home',
    code: 'GD',
    name: 'Đồ gia dụng',
    description: 'Đồ dùng nhà bếp, điện nhỏ',
    isActive: true,
    weight: 0.8,
    supplierKey: 'saigonhome',
  },
  {
    key: 'frozen',
    code: 'DL',
    name: 'Đồ đông lạnh',
    description: 'Xúc xích, cá viên, kem',
    isActive: true,
    weight: 1.6,
    supplierKey: 'dalatgreen',
  },
  {
    key: 'veggie',
    code: 'RC',
    name: 'Rau củ quả đóng gói',
    description: 'Rau củ sơ chế đóng gói',
    isActive: true,
    weight: 1.4,
    supplierKey: 'dalatgreen',
  },
  {
    key: 'stationery',
    code: 'VP',
    name: 'Văn phòng phẩm',
    description: 'Ngừng kinh doanh nhóm hàng này',
    isActive: false,
    weight: 0.3,
    supplierKey: 'saigonhome',
  },
];

export const SUPPLIERS: DemoSupplier[] = [
  {
    key: 'anphat',
    name: 'Công ty TNHH Phân phối Nước giải khát An Phát',
    phone: '02838123456',
    email: 'kinhdoanh@anphat.example.vn',
    address: '125 Nguyễn Thị Thập, Phường Tân Phú, Quận 7, TP. Hồ Chí Minh',
    note: 'Giao hàng thứ 2 và thứ 5, công nợ 7 ngày',
    isActive: true,
  },
  {
    key: 'haiha',
    name: 'Công ty CP Bánh kẹo Hải Hà Miền Nam',
    phone: '02838654321',
    email: 'donhang@haiha-mn.example.vn',
    address: '48 Lũy Bán Bích, Phường Hòa Thạnh, Quận Tân Phú, TP. Hồ Chí Minh',
    note: 'Tối thiểu 2 triệu đồng/đơn',
    isActive: true,
  },
  {
    key: 'binhminh',
    name: 'Đại lý sữa Bình Minh',
    phone: '0903456789',
    email: 'binhminh.sua@example.vn',
    address: '17 Phan Văn Trị, Phường 10, Quận Gò Vấp, TP. Hồ Chí Minh',
    note: 'Hàng sữa cần bảo quản lạnh, giao buổi sáng',
    isActive: true,
  },
  {
    key: 'hoabinh',
    name: 'Đại lý Thực phẩm Hòa Bình',
    phone: '02837654321',
    email: 'hoabinh@example.vn',
    address: '230 Kinh Dương Vương, Phường An Lạc, Quận Bình Tân, TP. Hồ Chí Minh',
    note: 'Chiết khấu 2% khi thanh toán trong 3 ngày',
    isActive: true,
  },
  {
    key: 'namviet',
    name: 'Công ty TNHH Gia vị Nam Việt',
    phone: '02839112233',
    email: 'sales@namviet.example.vn',
    address: '9 Tân Hóa, Phường 14, Quận 6, TP. Hồ Chí Minh',
    note: 'Giao miễn phí đơn từ 3 triệu',
    isActive: true,
  },
  {
    key: 'achau',
    name: 'Công ty TNHH Hóa mỹ phẩm Á Châu',
    phone: '02838445566',
    email: 'hmp.achau@example.vn',
    address: '66 Hồng Bàng, Phường 12, Quận 5, TP. Hồ Chí Minh',
    note: 'Đổi trả hàng lỗi trong 7 ngày',
    isActive: true,
  },
  {
    key: 'saigonhome',
    name: 'Cửa hàng Gia dụng Sài Gòn Home',
    phone: '0988123123',
    email: 'saigonhome@example.vn',
    address: '301 Lê Văn Sỹ, Phường 1, Quận Tân Bình, TP. Hồ Chí Minh',
    note: 'Ngừng hợp tác từ giữa kỳ do giao hàng trễ nhiều lần',
    isActive: false,
  },
  {
    key: 'dalatgreen',
    name: 'Công ty TNHH Thực phẩm Đà Lạt Green',
    phone: '02633822888',
    email: 'order@dalatgreen.example.vn',
    address: '12 Phan Đình Phùng, Phường 1, TP. Đà Lạt, Lâm Đồng',
    note: 'Rau củ giao theo chuyến xe lạnh thứ 3 và thứ 6',
    isActive: true,
  },
];

/** Supplier that replaces the deactivated one for its categories. */
export const REPLACEMENT_SUPPLIER_KEY = 'achau';
export const DEACTIVATED_SUPPLIER_KEY = 'saigonhome';

function p(categoryKey: string, name: string, unit: string, price: number): DemoProductSpec {
  return { categoryKey, name, unit, price };
}

export const PRODUCTS: DemoProductSpec[] = [
  p('drink', 'Nước suối Aquafina 500ml', 'chai', 5000),
  p('drink', 'Nước suối Lavie 500ml', 'chai', 5000),
  p('drink', 'Nước suối Lavie 1.5L', 'chai', 8000),
  p('drink', 'Coca-Cola lon 330ml', 'lon', 10000),
  p('drink', 'Pepsi lon 330ml', 'lon', 10000),
  p('drink', '7Up lon 330ml', 'lon', 10000),
  p('drink', 'Sting dâu chai 330ml', 'chai', 10000),
  p('drink', 'Trà xanh Không Độ 455ml', 'chai', 10000),
  p('drink', 'Trà Olong Tea Plus 455ml', 'chai', 10000),
  p('drink', 'Nước tăng lực Red Bull 250ml', 'lon', 12000),
  p('drink', 'Cà phê sữa Highlands lon 235ml', 'lon', 15000),
  p('drink', 'Bia Tiger lon 330ml', 'lon', 18000),
  p('drink', 'Bia Saigon Lager lon 330ml', 'lon', 15000),
  p('drink', 'Bia 333 lon 330ml', 'lon', 12500),
  p('drink', 'Bia Tiger thùng 24 lon', 'thùng', 395000),
  p('drink', 'Nước cam Tropicana Twister 345ml', 'chai', 12000),
  p('drink', 'Nước dừa Cocoxim hộp 330ml', 'hộp', 15000),
  p('drink', 'Nước ngọt Mirinda cam chai 390ml', 'chai', 9000),
  p('candy', 'Bánh quy Oreo 137g', 'gói', 17000),
  p('candy', 'Bánh Chocopie hộp 12 cái', 'hộp', 62000),
  p('candy', 'Bánh Cosy cracker 360g', 'gói', 28500),
  p('candy', 'Kẹo Alpenliebe 120g', 'gói', 22000),
  p('candy', 'Kẹo cao su Doublemint gói 5 thanh', 'gói', 5500),
  p('candy', 'Snack Oishi tôm cay 40g', 'gói', 6000),
  p('candy', "Snack Lay's vị tự nhiên 52g", 'gói', 12000),
  p('candy', 'Bánh gạo One One 150g', 'gói', 18500),
  p('candy', 'Kẹo Mentos cuộn 37g', 'cuộn', 9000),
  p('candy', 'Socola KitKat 4 thanh 35g', 'thanh', 15500),
  p('candy', 'Bánh Hura Cake hộp 12 cái', 'hộp', 36000),
  p('candy', 'Bánh bông lan Solite cuộn', 'cuộn', 24000),
  p('candy', 'Kẹo dẻo Haribo Goldbears 80g', 'gói', 32000),
  p('candy', 'Bánh Karo kem cây 20 cái', 'hộp', 45000),
  p('milk', 'Sữa tươi Vinamilk 100% 1L', 'hộp', 33000),
  p('milk', 'Sữa tươi TH True Milk 180ml', 'hộp', 9000),
  p('milk', 'Sữa tươi TH True Milk 1L', 'hộp', 38500),
  p('milk', 'Sữa chua Vinamilk có đường 100g', 'hộp', 6500),
  p('milk', 'Sữa đặc Ông Thọ lon 380g', 'lon', 24500),
  p('milk', 'Sữa Dutch Lady dâu 180ml', 'hộp', 8500),
  p('milk', 'Phô mai Con Bò Cười 8 miếng', 'hộp', 36000),
  p('milk', 'Sữa đậu nành Fami 200ml', 'hộp', 6000),
  p('milk', 'Sữa Milo hộp 180ml', 'hộp', 9500),
  p('milk', 'Sữa bột Dielac Alpha Gold 400g', 'hộp', 195000),
  p('milk', 'Sữa chua uống Yakult lốc 5 chai', 'lốc', 28000),
  p('milk', 'Bơ Anchor muối 227g', 'hộp', 69000),
  p('milk', 'Sữa hạt óc chó Vinamilk 180ml', 'hộp', 12500),
  p('noodle', 'Mì Hảo Hảo tôm chua cay', 'gói', 4500),
  p('noodle', 'Mì Omachi sườn hầm', 'gói', 9000),
  p('noodle', 'Mì Gấu Đỏ gà', 'gói', 4000),
  p('noodle', 'Phở bò ăn liền Vifon', 'gói', 12000),
  p('noodle', 'Miến Phú Hương 200g', 'gói', 15500),
  p('noodle', 'Cháo Cây Thị thịt bằm', 'gói', 8500),
  p('noodle', 'Mì ly Modern lẩu thái', 'ly', 14000),
  p('noodle', 'Gạo ST25 túi 5kg', 'túi', 135000),
  p('noodle', 'Gạo thơm Jasmine túi 10kg', 'túi', 245000),
  p('noodle', 'Đậu xanh hạt 500g', 'gói', 28000),
  p('noodle', 'Nấm hương khô 100g', 'gói', 49000),
  p('noodle', 'Bún gạo khô 400g', 'gói', 17000),
  p('noodle', 'Hủ tiếu Nam Vang khô 500g', 'gói', 24500),
  p('noodle', 'Bánh tráng Tây Ninh 300g', 'gói', 19000),
  p('spice', 'Nước mắm Chin-su 500ml', 'chai', 38000),
  p('spice', 'Nước tương Maggi 300ml', 'chai', 22500),
  p('spice', 'Dầu ăn Simply 1L', 'chai', 62000),
  p('spice', 'Dầu ăn Tường An 2L', 'chai', 118000),
  p('spice', 'Đường tinh luyện Biên Hòa 1kg', 'túi', 27000),
  p('spice', 'Muối i-ốt Bạc Liêu 500g', 'gói', 5000),
  p('spice', 'Hạt nêm Knorr 900g', 'gói', 78000),
  p('spice', 'Bột ngọt Ajinomoto 400g', 'gói', 36000),
  p('spice', 'Tương ớt Chin-su 250g', 'chai', 17500),
  p('spice', 'Tiêu đen xay 50g', 'hộp', 25000),
  p('spice', 'Giấm gạo Nam Dương 500ml', 'chai', 14500),
  p('spice', 'Bột canh Hải Châu 200g', 'gói', 11000),
  p('beauty', 'Dầu gội Clear Mát lạnh 340g', 'chai', 98000),
  p('beauty', 'Sữa tắm Lifebuoy 500g', 'chai', 115000),
  p('beauty', 'Kem đánh răng P/S 200g', 'tuýp', 38000),
  p('beauty', 'Bột giặt Omo Matic 3kg', 'túi', 165000),
  p('beauty', 'Nước rửa chén Sunlight 750g', 'chai', 32000),
  p('beauty', 'Nước xả vải Comfort 3.2L', 'túi', 145000),
  p('beauty', 'Giấy vệ sinh Pulppy 10 cuộn', 'lốc', 68000),
  p('beauty', 'Khăn giấy rút Bless You 180 tờ', 'hộp', 12000),
  p('beauty', 'Băng vệ sinh Diana siêu thấm', 'gói', 28500),
  p('beauty', 'Bàn chải đánh răng Colgate', 'cái', 22000),
  p('beauty', 'Xà phòng Lifebuoy 90g', 'cục', 9500),
  p('beauty', 'Nước lau sàn Sunlight 1kg', 'chai', 52000),
  p('beauty', 'Dầu gội Sunsilk óng mượt 320g', 'chai', 89000),
  p('home', 'Chảo chống dính 24cm', 'cái', 185000),
  p('home', 'Ly thủy tinh 300ml', 'cái', 15000),
  p('home', 'Bộ hộp nhựa đựng thực phẩm 3 cái', 'bộ', 45000),
  p('home', 'Bình nước nhựa 1L', 'cái', 55000),
  p('home', 'Bật lửa Zippo mini', 'cái', 8000),
  p('home', 'Pin AA Con Ó vỉ 4 viên', 'vỉ', 22000),
  p('home', 'Bóng đèn LED 9W', 'cái', 35000),
  p('home', 'Ổ cắm điện 4 lỗ 3m', 'cái', 95000),
  p('home', 'Khăn tắm cotton 60x120', 'cái', 65000),
  p('home', 'Chổi quét nhà cán dài', 'cái', 42000),
  p('frozen', 'Xúc xích Vissan 5 cây', 'gói', 38000),
  p('frozen', 'Cá viên CP 500g', 'gói', 55000),
  p('frozen', 'Tôm viên Cầu Tre 200g', 'gói', 42000),
  p('frozen', 'Bánh bao Thọ Phát 4 cái', 'gói', 36000),
  p('frozen', 'Há cảo tôm 300g', 'gói', 58000),
  p('frozen', "Kem Wall's Cornetto", 'cây', 14000),
  p('frozen', 'Kem Merino ly vani', 'ly', 12000),
  p('frozen', 'Chả giò hải sản 400g', 'gói', 69000),
  p('frozen', 'Gà viên popcorn 300g', 'gói', 49000),
  p('frozen', 'Đậu bắp đông lạnh 300g', 'gói', 26000),
  p('veggie', 'Cà rốt baby 250g', 'gói', 18000),
  p('veggie', 'Khoai tây Đà Lạt 500g', 'gói', 32000),
  p('veggie', 'Cà chua bi hộp 250g', 'hộp', 28000),
  p('veggie', 'Xà lách thủy canh 150g', 'gói', 22000),
  p('veggie', 'Nấm đùi gà 200g', 'gói', 25000),
  p('veggie', 'Hành tây 500g', 'gói', 20000),
  p('veggie', 'Dưa leo baby 300g', 'gói', 18500),
  p('veggie', 'Bắp cải thảo cắt sẵn 400g', 'gói', 21000),
  p('veggie', 'Rau muống sơ chế 300g', 'gói', 15000),
  p('stationery', 'Bút bi Thiên Long 0.5mm', 'cái', 5000),
  p('stationery', 'Tập học sinh 96 trang', 'quyển', 9000),
  p('stationery', 'Băng keo trong 48mm', 'cuộn', 8500),
  p('stationery', 'Giấy A4 Double A 70gsm', 'ream', 85000),
];

export const REASONS_NEGATIVE = [
  'Hàng hỏng, vỡ bao bì',
  'Hàng hết hạn sử dụng, loại khỏi kệ',
  'Thất thoát khi kiểm đếm cuối tháng',
  'Chai vỡ khi vận chuyển nội bộ',
  'Hàng bị chuột cắn, hủy',
];
export const REASONS_POSITIVE = [
  'Tìm thấy hàng ở kho phụ, bổ sung vào tồn',
  'Nhập thiếu chứng từ đợt trước, điều chỉnh tăng',
  'Khách trả lại hàng nguyên seal, nhập lại kho',
];
export const REASONS_ZERO = [
  'Kiểm kê định kỳ, số liệu khớp',
  'Đếm lại sau khi khách phản ánh, số liệu khớp',
];

export const LAST_NAMES = [
  'Nguyễn',
  'Trần',
  'Lê',
  'Phạm',
  'Hoàng',
  'Huỳnh',
  'Phan',
  'Vũ',
  'Võ',
  'Đặng',
  'Bùi',
  'Đỗ',
  'Hồ',
  'Ngô',
  'Dương',
  'Lý',
];
export const MIDDLE_NAMES_FEMALE = [
  'Thị',
  'Ngọc',
  'Thanh',
  'Kim',
  'Minh',
  'Hồng',
  'Thu',
  'Phương',
  'Bảo',
];
export const MIDDLE_NAMES_MALE = [
  'Văn',
  'Hữu',
  'Minh',
  'Quốc',
  'Đức',
  'Anh',
  'Thanh',
  'Gia',
  'Trung',
];
export const FIRST_NAMES_FEMALE = [
  'Lan',
  'Hoa',
  'Mai',
  'Linh',
  'Trang',
  'Hương',
  'Thảo',
  'Nhung',
  'Yến',
  'Vy',
  'Ngân',
  'Huyền',
  'Dung',
  'Hạnh',
  'Chi',
];
export const FIRST_NAMES_MALE = [
  'Hùng',
  'Dũng',
  'Nam',
  'Tuấn',
  'Long',
  'Phúc',
  'Khoa',
  'Đạt',
  'Bình',
  'Cường',
  'Hải',
  'Sơn',
  'Thắng',
  'Quân',
  'Tín',
];
export const PHONE_PREFIXES = [
  '090',
  '093',
  '089',
  '070',
  '079',
  '077',
  '076',
  '078',
  '091',
  '094',
  '088',
  '083',
  '084',
  '085',
  '081',
  '082',
  '032',
  '033',
  '034',
  '035',
  '036',
  '037',
  '038',
  '039',
  '056',
  '058',
  '059',
  '097',
  '098',
  '086',
  '096',
];
export const USER_AGENTS = [
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36',
  'Mozilla/5.0 (iPad; CPU OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Edg/126.0 Safari/537.36',
];
