/** Machine-readable error codes returned in the `code` field of the error envelope. */
export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  DUPLICATE_VALUE = 'DUPLICATE_VALUE',
  RESOURCE_IN_USE = 'RESOURCE_IN_USE',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  USER_NOT_FOUND = 'USER_NOT_FOUND',
  CANNOT_LOCK_SELF = 'CANNOT_LOCK_SELF',
  LAST_ACTIVE_ADMIN = 'LAST_ACTIVE_ADMIN',

  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  CATEGORY_INACTIVE = 'CATEGORY_INACTIVE',
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  PRODUCT_UNAVAILABLE = 'PRODUCT_UNAVAILABLE',
  SUPPLIER_NOT_FOUND = 'SUPPLIER_NOT_FOUND',
  SUPPLIER_INACTIVE = 'SUPPLIER_INACTIVE',
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',

  INVALID_QUANTITY = 'INVALID_QUANTITY',
  INSUFFICIENT_STOCK = 'INSUFFICIENT_STOCK',
  INVALID_DISCOUNT = 'INVALID_DISCOUNT',
  INVALID_PAYMENT = 'INVALID_PAYMENT',
  SALE_NOT_FOUND = 'SALE_NOT_FOUND',

  PURCHASE_NOT_FOUND = 'PURCHASE_NOT_FOUND',
  PURCHASE_ALREADY_RECEIVED = 'PURCHASE_ALREADY_RECEIVED',
  PURCHASE_CANCELLED = 'PURCHASE_CANCELLED',
  INVALID_PURCHASE_LINE = 'INVALID_PURCHASE_LINE',

  STOCK_CONFLICT = 'STOCK_CONFLICT',

  INVALID_DATE_RANGE = 'INVALID_DATE_RANGE',
}
